base_url = "https://ryanponce.com"
title = "Ryan Ponce"
description = "Ryan Ponce's personal website"
author = "Ryan Ponce"

compile_sass = false
minify_html = true

[markdown]
lazy_async_image = true
